region := env("AWS_REGION", "eu-west-1")

export AWS_PAGER := ""

tf-apply:
    tofu init
    tofu apply -auto-approve \
        -var "region={{region}}" \
        -var "script_path={{justfile_directory()}}/main.py"

tf-destroy:
    #!/bin/bash -e
    tmp=$(mktemp)
    tofu destroy -auto-approve -var "region={{region}}" -var "script_path=$tmp"
    rm "$tmp"

tf-fmt:
    tofu fmt .
