region := env("AWS_REGION", "eu-west-1")

tf-apply:
    tofu init
    tofu apply -auto-approve -var "region={{region}}"

tf-destroy:
    tofu destroy -auto-approve -var "region={{region}}"

tf-fmt:
    tofu fmt .
